// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: definition.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Function int32

const (
	Function_POWER_TOGGLE Function = 0
	Function_UP           Function = 1
	Function_RIGHT        Function = 2
	Function_DOWN         Function = 3
	Function_LEFT         Function = 4
	Function_OK           Function = 5
	Function_BACK         Function = 6
	Function_EXIT         Function = 7
	Function_POWER_ON     Function = 8
	Function_POWER_OFF    Function = 9
	Function_VOLUME_UP    Function = 10
	Function_VOLUME_DOWN  Function = 11
	Function_PROGRAM_UP   Function = 12
	Function_PROGRAM_DOWN Function = 13
	Function_ZERO         Function = 20
	Function_ONE          Function = 21
	Function_TWO          Function = 22
	Function_THREE        Function = 23
	Function_FOUR         Function = 24
	Function_FIVE         Function = 25
	Function_SIX          Function = 26
	Function_SEVEN        Function = 27
	Function_EIGHT        Function = 28
	Function_NINE         Function = 29
	Function_VOLUME_MUTE  Function = 30
	Function_PLAY         Function = 31
	Function_PAUSE        Function = 32
	Function_PLAY_PAUSE   Function = 33
	Function_STOP         Function = 34
	Function_FAST_FORWARD Function = 35
	Function_FAST_REWIND  Function = 36
)

// Enum value maps for Function.
var (
	Function_name = map[int32]string{
		0:  "POWER_TOGGLE",
		1:  "UP",
		2:  "RIGHT",
		3:  "DOWN",
		4:  "LEFT",
		5:  "OK",
		6:  "BACK",
		7:  "EXIT",
		8:  "POWER_ON",
		9:  "POWER_OFF",
		10: "VOLUME_UP",
		11: "VOLUME_DOWN",
		12: "PROGRAM_UP",
		13: "PROGRAM_DOWN",
		20: "ZERO",
		21: "ONE",
		22: "TWO",
		23: "THREE",
		24: "FOUR",
		25: "FIVE",
		26: "SIX",
		27: "SEVEN",
		28: "EIGHT",
		29: "NINE",
		30: "VOLUME_MUTE",
		31: "PLAY",
		32: "PAUSE",
		33: "PLAY_PAUSE",
		34: "STOP",
		35: "FAST_FORWARD",
		36: "FAST_REWIND",
	}
	Function_value = map[string]int32{
		"POWER_TOGGLE": 0,
		"UP":           1,
		"RIGHT":        2,
		"DOWN":         3,
		"LEFT":         4,
		"OK":           5,
		"BACK":         6,
		"EXIT":         7,
		"POWER_ON":     8,
		"POWER_OFF":    9,
		"VOLUME_UP":    10,
		"VOLUME_DOWN":  11,
		"PROGRAM_UP":   12,
		"PROGRAM_DOWN": 13,
		"ZERO":         20,
		"ONE":          21,
		"TWO":          22,
		"THREE":        23,
		"FOUR":         24,
		"FIVE":         25,
		"SIX":          26,
		"SEVEN":        27,
		"EIGHT":        28,
		"NINE":         29,
		"VOLUME_MUTE":  30,
		"PLAY":         31,
		"PAUSE":        32,
		"PLAY_PAUSE":   33,
		"STOP":         34,
		"FAST_FORWARD": 35,
		"FAST_REWIND":  36,
	}
)

func (x Function) Enum() *Function {
	p := new(Function)
	*p = x
	return p
}

func (x Function) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Function) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_proto_enumTypes[0].Descriptor()
}

func (Function) Type() protoreflect.EnumType {
	return &file_definition_proto_enumTypes[0]
}

func (x Function) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Function.Descriptor instead.
func (Function) EnumDescriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{0}
}

type Remote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MqttTopicPrefix string `protobuf:"bytes,2,opt,name=mqttTopicPrefix,proto3" json:"mqttTopicPrefix,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Remote) Reset() {
	*x = Remote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remote) ProtoMessage() {}

func (x *Remote) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remote.ProtoReflect.Descriptor instead.
func (*Remote) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{0}
}

func (x *Remote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Remote) GetMqttTopicPrefix() string {
	if x != nil {
		return x.MqttTopicPrefix
	}
	return ""
}

func (x *Remote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoteStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteId    string   `protobuf:"bytes,1,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	Online      bool     `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Lifesign    string   `protobuf:"bytes,3,opt,name=lifesign,proto3" json:"lifesign,omitempty"`
	LastCommand *Command `protobuf:"bytes,4,opt,name=lastCommand,proto3" json:"lastCommand,omitempty"`
}

func (x *RemoteStatus) Reset() {
	*x = RemoteStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteStatus) ProtoMessage() {}

func (x *RemoteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteStatus.ProtoReflect.Descriptor instead.
func (*RemoteStatus) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteStatus) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *RemoteStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *RemoteStatus) GetLifesign() string {
	if x != nil {
		return x.Lifesign
	}
	return ""
}

func (x *RemoteStatus) GetLastCommand() *Command {
	if x != nil {
		return x.LastCommand
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command    *NECCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Rc6Command *RC6Command `protobuf:"bytes,3,opt,name=rc6_command,json=rc6Command,proto3" json:"rc6_command,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetCommand() *NECCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Command) GetRc6Command() *RC6Command {
	if x != nil {
		return x.Rc6Command
	}
	return nil
}

type NECCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId int32 `protobuf:"varint,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Command  int32 `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *NECCommand) Reset() {
	*x = NECCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NECCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NECCommand) ProtoMessage() {}

func (x *NECCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NECCommand.ProtoReflect.Descriptor instead.
func (*NECCommand) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{3}
}

func (x *NECCommand) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *NECCommand) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

type RC6Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode        int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Control     int32 `protobuf:"varint,2,opt,name=control,proto3" json:"control,omitempty"`
	Information int32 `protobuf:"varint,3,opt,name=information,proto3" json:"information,omitempty"`
}

func (x *RC6Command) Reset() {
	*x = RC6Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RC6Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RC6Command) ProtoMessage() {}

func (x *RC6Command) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RC6Command.ProtoReflect.Descriptor instead.
func (*RC6Command) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{4}
}

func (x *RC6Command) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *RC6Command) GetControl() int32 {
	if x != nil {
		return x.Control
	}
	return 0
}

func (x *RC6Command) GetInformation() int32 {
	if x != nil {
		return x.Information
	}
	return 0
}

type Scene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instructions []*Instruction `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
}

func (x *Scene) Reset() {
	*x = Scene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{5}
}

func (x *Scene) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type Repeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times       int32        `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
	Instruction *Instruction `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
}

func (x *Repeat) Reset() {
	*x = Repeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Repeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeat) ProtoMessage() {}

func (x *Repeat) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeat.ProtoReflect.Descriptor instead.
func (*Repeat) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{6}
}

func (x *Repeat) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *Repeat) GetInstruction() *Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

type Instruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Scene   *Scene   `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Repeat  *Repeat  `protobuf:"bytes,3,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Wait    *Wait    `protobuf:"bytes,4,opt,name=wait,proto3" json:"wait,omitempty"`
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{7}
}

func (x *Instruction) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Instruction) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *Instruction) GetRepeat() *Repeat {
	if x != nil {
		return x.Repeat
	}
	return nil
}

func (x *Instruction) GetWait() *Wait {
	if x != nil {
		return x.Wait
	}
	return nil
}

type Wait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds      int32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Milliseconds int32 `protobuf:"varint,2,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
}

func (x *Wait) Reset() {
	*x = Wait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wait) ProtoMessage() {}

func (x *Wait) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wait.ProtoReflect.Descriptor instead.
func (*Wait) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{8}
}

func (x *Wait) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Wait) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type DescriptiveScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SortKey     int32    `protobuf:"varint,4,opt,name=sortKey,proto3" json:"sortKey,omitempty"`
	Scene       *Scene   `protobuf:"bytes,5,opt,name=scene,proto3" json:"scene,omitempty"`
	Function    Function `protobuf:"varint,6,opt,name=function,proto3,enum=remote.Function" json:"function,omitempty"`
}

func (x *DescriptiveScene) Reset() {
	*x = DescriptiveScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescriptiveScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptiveScene) ProtoMessage() {}

func (x *DescriptiveScene) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptiveScene.ProtoReflect.Descriptor instead.
func (*DescriptiveScene) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{9}
}

func (x *DescriptiveScene) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescriptiveScene) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescriptiveScene) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescriptiveScene) GetSortKey() int32 {
	if x != nil {
		return x.SortKey
	}
	return 0
}

func (x *DescriptiveScene) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *DescriptiveScene) GetFunction() Function {
	if x != nil {
		return x.Function
	}
	return Function_POWER_TOGGLE
}

type Theater struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RemoteId string              `protobuf:"bytes,3,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	SortKey  int32               `protobuf:"varint,4,opt,name=sortKey,proto3" json:"sortKey,omitempty"`
	Scenes   []*DescriptiveScene `protobuf:"bytes,5,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Icon     string              `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *Theater) Reset() {
	*x = Theater{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theater) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theater) ProtoMessage() {}

func (x *Theater) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theater.ProtoReflect.Descriptor instead.
func (*Theater) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{10}
}

func (x *Theater) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theater) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theater) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *Theater) GetSortKey() int32 {
	if x != nil {
		return x.SortKey
	}
	return 0
}

func (x *Theater) GetScenes() []*DescriptiveScene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *Theater) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type TheatersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theaters []*Theater `protobuf:"bytes,1,rep,name=theaters,proto3" json:"theaters,omitempty"`
}

func (x *TheatersResponse) Reset() {
	*x = TheatersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheatersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheatersResponse) ProtoMessage() {}

func (x *TheatersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheatersResponse.ProtoReflect.Descriptor instead.
func (*TheatersResponse) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{11}
}

func (x *TheatersResponse) GetTheaters() []*Theater {
	if x != nil {
		return x.Theaters
	}
	return nil
}

type RemoteQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoteQueryParams) Reset() {
	*x = RemoteQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteQueryParams) ProtoMessage() {}

func (x *RemoteQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteQueryParams.ProtoReflect.Descriptor instead.
func (*RemoteQueryParams) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteQueryParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlaySceneParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteId string `protobuf:"bytes,1,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	Scene    *Scene `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *PlaySceneParams) Reset() {
	*x = PlaySceneParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaySceneParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySceneParams) ProtoMessage() {}

func (x *PlaySceneParams) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySceneParams.ProtoReflect.Descriptor instead.
func (*PlaySceneParams) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{13}
}

func (x *PlaySceneParams) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *PlaySceneParams) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type PlayCommandParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteId string   `protobuf:"bytes,1,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	Command  *Command `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *PlayCommandParams) Reset() {
	*x = PlayCommandParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayCommandParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCommandParams) ProtoMessage() {}

func (x *PlayCommandParams) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCommandParams.ProtoReflect.Descriptor instead.
func (*PlayCommandParams) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{14}
}

func (x *PlayCommandParams) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *PlayCommandParams) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type PlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{15}
}

func (x *PlayResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetTheaterQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteId string   `protobuf:"bytes,1,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	Theater  *Theater `protobuf:"bytes,2,opt,name=theater,proto3" json:"theater,omitempty"`
}

func (x *SetTheaterQueryParams) Reset() {
	*x = SetTheaterQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTheaterQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTheaterQueryParams) ProtoMessage() {}

func (x *SetTheaterQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTheaterQueryParams.ProtoReflect.Descriptor instead.
func (*SetTheaterQueryParams) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{16}
}

func (x *SetTheaterQueryParams) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *SetTheaterQueryParams) GetTheater() *Theater {
	if x != nil {
		return x.Theater
	}
	return nil
}

type RemoveTheaterQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteId  string `protobuf:"bytes,1,opt,name=remoteId,proto3" json:"remoteId,omitempty"`
	TheaterId string `protobuf:"bytes,2,opt,name=theaterId,proto3" json:"theaterId,omitempty"`
}

func (x *RemoveTheaterQueryParams) Reset() {
	*x = RemoveTheaterQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTheaterQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTheaterQueryParams) ProtoMessage() {}

func (x *RemoveTheaterQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTheaterQueryParams.ProtoReflect.Descriptor instead.
func (*RemoveTheaterQueryParams) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveTheaterQueryParams) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *RemoveTheaterQueryParams) GetTheaterId() string {
	if x != nil {
		return x.TheaterId
	}
	return ""
}

var File_definition_proto protoreflect.FileDescriptor

var file_definition_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x71, 0x74, 0x74, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d,
	0x71, 0x74, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x66, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x66, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x12, 0x31, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x2e, 0x4e, 0x45, 0x43, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x72, 0x63, 0x36, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x2e, 0x52, 0x43, 0x36, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0a, 0x72,
	0x63, 0x36, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x4e, 0x45, 0x43,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x5c, 0x0a,
	0x0a, 0x52, 0x43, 0x36, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x05, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x55, 0x0a,
	0x06, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x35, 0x0a,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x23, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x04,
	0x77, 0x61, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x52, 0x04, 0x77, 0x61, 0x69, 0x74, 0x22, 0x44,
	0x0a, 0x04, 0x57, 0x61, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x2c,
	0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa9, 0x01, 0x0a,
	0x07, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74,
	0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x06, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x10, 0x54, 0x68, 0x65, 0x61,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08,
	0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x52,
	0x08, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x52,
	0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x22, 0x5a, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x1e,
	0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x5e,
	0x0a, 0x15, 0x73, 0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x54, 0x68,
	0x65, 0x61, 0x74, 0x65, 0x72, 0x52, 0x07, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x22, 0x54,
	0x0a, 0x18, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x65, 0x61, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x2a, 0x85, 0x03, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x54, 0x4f, 0x47, 0x47, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x49, 0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04,
	0x45, 0x58, 0x49, 0x54, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f,
	0x4f, 0x4e, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x4f, 0x46,
	0x46, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x5f, 0x55, 0x50,
	0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x55,
	0x50, 0x10, 0x0c, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x44,
	0x4f, 0x57, 0x4e, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x45, 0x52, 0x4f, 0x10, 0x14, 0x12,
	0x07, 0x0a, 0x03, 0x4f, 0x4e, 0x45, 0x10, 0x15, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x57, 0x4f, 0x10,
	0x16, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x48, 0x52, 0x45, 0x45, 0x10, 0x17, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x4f, 0x55, 0x52, 0x10, 0x18, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x56, 0x45, 0x10, 0x19,
	0x12, 0x07, 0x0a, 0x03, 0x53, 0x49, 0x58, 0x10, 0x1a, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x45, 0x56,
	0x45, 0x4e, 0x10, 0x1b, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x49, 0x47, 0x48, 0x54, 0x10, 0x1c, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10, 0x1d, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x4f, 0x4c,
	0x55, 0x4d, 0x45, 0x5f, 0x4d, 0x55, 0x54, 0x45, 0x10, 0x1e, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c,
	0x41, 0x59, 0x10, 0x1f, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x55, 0x53, 0x45, 0x10, 0x20, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41, 0x59, 0x5f, 0x50, 0x41, 0x55, 0x53, 0x45, 0x10, 0x21, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x22, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x41, 0x53,
	0x54, 0x5f, 0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44, 0x10, 0x23, 0x12, 0x0f, 0x0a, 0x0b, 0x46,
	0x41, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x57, 0x49, 0x4e, 0x44, 0x10, 0x24, 0x32, 0xdb, 0x03, 0x0a,
	0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36,
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0e, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x54, 0x68, 0x65,
	0x61, 0x74, 0x65, 0x72, 0x73, 0x4f, 0x66, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x54, 0x68, 0x65, 0x61,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a,
	0x73, 0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x2e, 0x73, 0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x2e, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x65,
	0x61, 0x74, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e,
	0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x6c,
	0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_definition_proto_rawDescOnce sync.Once
	file_definition_proto_rawDescData = file_definition_proto_rawDesc
)

func file_definition_proto_rawDescGZIP() []byte {
	file_definition_proto_rawDescOnce.Do(func() {
		file_definition_proto_rawDescData = protoimpl.X.CompressGZIP(file_definition_proto_rawDescData)
	})
	return file_definition_proto_rawDescData
}

var file_definition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_definition_proto_goTypes = []interface{}{
	(Function)(0),                    // 0: remote.Function
	(*Remote)(nil),                   // 1: remote.Remote
	(*RemoteStatus)(nil),             // 2: remote.RemoteStatus
	(*Command)(nil),                  // 3: remote.Command
	(*NECCommand)(nil),               // 4: remote.NECCommand
	(*RC6Command)(nil),               // 5: remote.RC6Command
	(*Scene)(nil),                    // 6: remote.Scene
	(*Repeat)(nil),                   // 7: remote.Repeat
	(*Instruction)(nil),              // 8: remote.Instruction
	(*Wait)(nil),                     // 9: remote.Wait
	(*DescriptiveScene)(nil),         // 10: remote.DescriptiveScene
	(*Theater)(nil),                  // 11: remote.Theater
	(*TheatersResponse)(nil),         // 12: remote.TheatersResponse
	(*RemoteQueryParams)(nil),        // 13: remote.remoteQueryParams
	(*PlaySceneParams)(nil),          // 14: remote.playSceneParams
	(*PlayCommandParams)(nil),        // 15: remote.playCommandParams
	(*PlayResponse)(nil),             // 16: remote.PlayResponse
	(*SetTheaterQueryParams)(nil),    // 17: remote.setTheaterQueryParams
	(*RemoveTheaterQueryParams)(nil), // 18: remote.removeTheaterQueryParams
}
var file_definition_proto_depIdxs = []int32{
	3,  // 0: remote.RemoteStatus.lastCommand:type_name -> remote.Command
	4,  // 1: remote.Command.command:type_name -> remote.NECCommand
	5,  // 2: remote.Command.rc6_command:type_name -> remote.RC6Command
	8,  // 3: remote.Scene.instructions:type_name -> remote.Instruction
	8,  // 4: remote.Repeat.instruction:type_name -> remote.Instruction
	3,  // 5: remote.Instruction.command:type_name -> remote.Command
	6,  // 6: remote.Instruction.scene:type_name -> remote.Scene
	7,  // 7: remote.Instruction.repeat:type_name -> remote.Repeat
	9,  // 8: remote.Instruction.wait:type_name -> remote.Wait
	6,  // 9: remote.DescriptiveScene.scene:type_name -> remote.Scene
	0,  // 10: remote.DescriptiveScene.function:type_name -> remote.Function
	10, // 11: remote.Theater.scenes:type_name -> remote.DescriptiveScene
	11, // 12: remote.TheatersResponse.theaters:type_name -> remote.Theater
	6,  // 13: remote.playSceneParams.scene:type_name -> remote.Scene
	3,  // 14: remote.playCommandParams.command:type_name -> remote.Command
	11, // 15: remote.setTheaterQueryParams.theater:type_name -> remote.Theater
	13, // 16: remote.remoteService.getRemote:input_type -> remote.remoteQueryParams
	13, // 17: remote.remoteService.getTheatersOf:input_type -> remote.remoteQueryParams
	17, // 18: remote.remoteService.setTheater:input_type -> remote.setTheaterQueryParams
	18, // 19: remote.remoteService.removeTheater:input_type -> remote.removeTheaterQueryParams
	13, // 20: remote.remoteService.getStatus:input_type -> remote.remoteQueryParams
	14, // 21: remote.remoteService.playScene:input_type -> remote.playSceneParams
	15, // 22: remote.remoteService.playCommand:input_type -> remote.playCommandParams
	1,  // 23: remote.remoteService.getRemote:output_type -> remote.Remote
	12, // 24: remote.remoteService.getTheatersOf:output_type -> remote.TheatersResponse
	12, // 25: remote.remoteService.setTheater:output_type -> remote.TheatersResponse
	12, // 26: remote.remoteService.removeTheater:output_type -> remote.TheatersResponse
	2,  // 27: remote.remoteService.getStatus:output_type -> remote.RemoteStatus
	16, // 28: remote.remoteService.playScene:output_type -> remote.PlayResponse
	16, // 29: remote.remoteService.playCommand:output_type -> remote.PlayResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_definition_proto_init() }
func file_definition_proto_init() {
	if File_definition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_definition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NECCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RC6Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Repeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescriptiveScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theater); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheatersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaySceneParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayCommandParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTheaterQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTheaterQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_definition_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_definition_proto_goTypes,
		DependencyIndexes: file_definition_proto_depIdxs,
		EnumInfos:         file_definition_proto_enumTypes,
		MessageInfos:      file_definition_proto_msgTypes,
	}.Build()
	File_definition_proto = out.File
	file_definition_proto_rawDesc = nil
	file_definition_proto_goTypes = nil
	file_definition_proto_depIdxs = nil
}
